version: '3.7'
services: 
  kong:
    image: kong:${TAG-latest}
    env_file: 
      - kong.env
    volumes: 
      - ./kong.yaml:/config/kong.yaml
    networks:
      - kong-net
    ports: 
      - 127.0.0.1:8001:8001
      - 127.0.0.1:8444:8444
      - 8000:8000
      - 8443:8443

networks: 
  kong-net:
    external: true